language: node_js
services:
  - docker
node_js:
  - 12.16.1
cache: yarn
addons:
  organization: 'inseefrlab'
install:
  - yarn config set registry https://registry.npmjs.org
  - yarn install
script:
  - yarn test-coverage
  - yarn build
after_script:
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
  - bash scripts/deploy.sh
deploy:
  - provider: script
    skip_cleanup: true
    script:
      docker build -t inseefrlab/onyxia-ui:latest . && echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      && docker push inseefrlab/onyxia-ui:latest
    on:
      branch: master
  - provider: script
    skip_cleanup: true
    script:
      docker build -t inseefrlab/onyxia-ui:$TRAVIS_TAG . && echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      && docker push inseefrlab/onyxia-ui:$TRAVIS_TAG
    on:
      tags: true
